# Generated by Django 6.0 on 2025-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='bodyweight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
